# Generated by Django 3.2.5 on 2021-09-06 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notebook', '0003_alter_contact_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='phone',
        ),
    ]
